# Generated by Django 2.0.3 on 2018-04-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compensations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Compensação')),
                ('date_start', models.DateTimeField(verbose_name='Data de início')),
                ('date_end', models.DateTimeField(verbose_name='Data fim')),
            ],
        ),
        migrations.CreateModel(
            name='CompensationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo de compensação')),
            ],
        ),
        migrations.CreateModel(
            name='Selic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('period', models.DateTimeField(verbose_name='Período')),
            ],
        ),
    ]
