# Generated by Django 2.0.3 on 2018-04-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Compensação')),
                ('date_start', models.DateField(verbose_name='Data de início')),
                ('date_end', models.DateField(verbose_name='Data fim')),
                ('pdf', models.FileField(upload_to='compensacoes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Businesses.Businesses')),
            ],
        ),
        migrations.CreateModel(
            name='CompensationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo de compensação')),
            ],
        ),
        migrations.CreateModel(
            name='Selic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('period', models.DateField(verbose_name='Período')),
            ],
        ),
        migrations.AddField(
            model_name='compensations',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compensacoes.CompensationTypes'),
        ),
    ]
