# Generated by Django 2.0.3 on 2018-04-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0001_initial'),
        ('Compensacoes', '0002_auto_20180404_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensations',
            name='id',
        ),
        migrations.AddField(
            model_name='compensations',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Businesses.Businesses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensations',
            name='tipo',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Compensacoes.CompensationTypes'),
            preserve_default=False,
        ),
    ]
