# Generated by Django 2.0.3 on 2018-04-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compensacoes', '0003_auto_20180410_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensations',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compensations',
            name='tipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Compensacoes.CompensationTypes'),
        ),
    ]
