# Generated by Django 2.0.3 on 2018-04-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compensacoes', '0004_auto_20180410_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensations',
            name='pdf',
            field=models.FileField(default=0, upload_to='compensacoes'),
            preserve_default=False,
        ),
    ]
