# Generated by Django 2.0.3 on 2018-04-11 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compensacoes', '0005_compensations_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensations',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compensacoes.CompensationTypes'),
        ),
    ]
