# Generated by Django 2.0.3 on 2018-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compensacoes', '0006_auto_20180411_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selic',
            name='period',
            field=models.DateField(verbose_name='Período'),
        ),
    ]
